#!/bin/sh
# prerm: pre-removal script for bitprotector
set -e

case "$1" in
    remove|purge)
        if systemctl is-active bitprotector >/dev/null 2>&1; then
            systemctl stop bitprotector
        fi
        if systemctl is-enabled bitprotector >/dev/null 2>&1; then
            systemctl disable bitprotector
        fi
    ;;
esac

#DEBHELPER#

exit 0
